### PR TITLE
Fix license violation

### PR DESCRIPTION
**Pull request by rugk**
The source code is licensed under the GPLv3. That [also means](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)) you have to credit the original author.

### CODE REVIEW

**Comment by pidiet** [comment]
@CHEF-KOCH is there any difference between the original (https://notabug.org/maloe/ASN_IPFire_Script) and your version published here?

**Comment by CHEF-KOCH** [comment]
Yes, mine first 3 entire months first.

**Comment by pidiet** [comment]
You didn't fixed the license violation? really?

**Comment by maikcocketz** [comment]
**CHEF-KOCH was first, Mike Kuketz and maloe stole the script from him. Go away, trolls! Donate for good work: https://github.com/CHEF-KOCH/Donations**

**Pull request closed without merging**
